### ISSUE TITLE
可以正常连上直播，但是没画面，一直在加载，是不是没有输入服务器地址

### ISSUE THREAD

**Issue by mufeiyu-ayu** [yielde/bilibili-mac#1]

**Comment by mufeiyu-ayu** [comment]
我的问题不好意思

**Comment by yielde** [comment]
没有使用推流软件推流吧
1. 点击开始直播是获取了推流码，推流码是使用第三方软件需要填入的地址，点击【开播】会出现推流码地址
<img width="851" alt="image" src="https://github.com/user-attachments/assets/db79ae48-ecc1-492a-b7ee-caa1f6a9556b">
2. 使用OBS软件进行推流，OBS点击设置->直播，服务器填入第一行，推流码填入第二行
<img width="799" alt="image" src="https://github.com/user-attachments/assets/741ea4bc-d8a6-4e9e-8073-b6fc166af881">
3. 填好之后点击开始直播，这时候就开始直播了
<img width="745" alt="image" src="https://github.com/user-attachments/assets/78a47ca1-6534-4904-91a4-da3944be25f5">
4. 弹幕功能是需要blivechat先拿个连接，copy到这里，然后点击弹幕，就可以弹窗啦
<img width="542" alt="image" src="https://github.com/user-attachments/assets/9602ae60-d977-49b0-83c7-be533b0cb914">
