### ISSUE TITLE
似乎还需要一条命令才能运行

### ISSUE THREAD

**Issue by TheAutomatic** [yielde/bilibili-mac#2]
sudo xattr -r -d com.apple.quarantine /path/to/MyApp.app
要删除app来自网络的属性，不然还是打不开，提示百度网盘下载的XXX损坏。
话说能传一个release吗？度盘实在是太慢了

**Comment by yielde** [comment]
so。。。你的环境是需要加这条命令吗。我测试用的是 macOS Sonoma 14.6.1，就按照readme里面的步骤可以运行，可能是设置隐私与安全性->任何来源的作用。

刚上传了一个release~

**Comment by TheAutomatic** [comment]
> so。。。你的环境是需要加这条命令吗。我测试用的是 macOS Sonoma 14.6.1，就按照readme里面的步骤可以运行，可能是设置隐私与安全性->任何来源的作用。
> 
> 刚上传了一个release~

是的，我开了未知来源也有这个问题。最早是有次用python写一个程序先传nas，下载之后发现无法运行，搜到有com.apple.quarantine这个东西，这次也是一样解决的

**Comment by TheAutomatic** [comment]
> so。。。你的环境是需要加这条命令吗。我测试用的是 macOS Sonoma 14.6.1，就按照readme里面的步骤可以运行，可能是设置隐私与安全性->任何来源的作用。
> 
> 刚上传了一个release~

是的，我开了未知来源也有这个问题。最早是有次用python写一个程序先传nas，下载之后发现无法运行，搜到有com.apple.quarantine这个东西，这次也是一样解决的

**Comment by yielde** [comment]
明白了，非常感谢，我后面把它加到readme里面
